In [29]:
import pandas as pd
df=pd.read_csv("used_cars_messy.csv")
print(df.head(10))
print(df.info())
print(df.describe())
print(df.shape)
df.drop_duplicates(inplace=True)
df

   Unnamed: 0            car_name     brand        model  vehicle_age  \
0        2581      Renault Duster   Renault       Duster            7
1         224      Maruti Wagon R    Maruti      Wagon R            3
2        1803          Honda City     Honda         City            3
3        2728    Mahindra Scorpio  Mahindra      Scorpio            6
4       14160     Mahindra XUV500  Mahindra       XUV500            4
5        4259         Hyundai i10   Hyundai          i10           12
6        2128         Hyundai i20   Hyundai          i20           12
7        6137      Maruti Wagon R    Maruti      Wagon R            7
8       16919      Ford Freestyle      Ford    Freestyle            2
9        2837  Maruti Swift Dzire    Maruti  Swift Dzire           10

  km_driven seller_type fuel_type transmission_type mileage  engine  \
0     67647      Dealer    Diesel            Manual   19.87  1461.0
1     52000      Dealer       CNG            Manual   33.54   998.0
2     48959      Dealer    Petrol            Manual     NaN  1497.0
3     82000      dealer    Diesel            Manual    15.4  2179.0
4     34000      Dealer    Diesel         Automatic    16.0  2179.0
5     73000      Dealer    Petrol            Manual   20.36  1197.0
6     88000      Dealer    Petrol            Manual    18.5     NaN
7     50000  Individual    Petrol            Manual   20.51     NaN
8     30000  individual    Diesel            Manual    24.4  1498.0
9     75220      Dealer    Diesel            Manual    19.3  1248.0

   max_power  seats  selling_price
0      83.80    5.0       575000.0
1      67.04    5.0       435000.0
2     117.60    5.0       875000.0
3        NaN    8.0       925000.0
4     140.00    7.0      1175000.0
5      78.90    5.0       190000.0
6      80.00    5.0       275000.0
7      67.04    5.0       351000.0
8      98.63    5.0       775000.0
9      73.90    5.0       390000.0
<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB
None
         Unnamed: 0   vehicle_age        engine     max_power         seats  \
count  15661.000000  15661.000000  13792.000000  14862.000000  15218.000000
mean    9808.189643      6.036843   1480.489342    100.513582      5.324418
std     5642.981540      3.015072    511.446057     42.854632      0.805993
min        0.000000      0.000000    793.000000     38.400000      0.000000
25%     4901.000000      4.000000   1197.000000     74.000000      5.000000
50%     9858.000000      6.000000   1248.000000     88.500000      5.000000
75%    14666.000000      8.000000   1582.000000    117.300000      5.000000
max    19543.000000     29.000000   6592.000000    626.000000      9.000000

       selling_price
count   1.550300e+04
mean    1.032764e+06
std     1.607380e+07
min     5.000000e+02
25%     3.850000e+05
50%     5.550000e+05
75%     8.250000e+05
max     1.000000e+09
(15661, 14)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [8]:
df["brand"]=df["brand"].str.strip()
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [9]:
df["brand"]=df["brand"].str.lower()
df.head(10)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
5,4259,Hyundai i10,hyundai,i10,12,73000,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,2128,Hyundai i20,hyundai,i20,12,88000,Dealer,Petrol,Manual,18.5,NaN,80.00,5.0,275000.0
7,6137,Maruti Wagon R,maruti,Wagon R,7,50000,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,16919,Ford Freestyle,ford,Freestyle,2,30000,individual,Diesel,Manual,24.4,1498.0,98.63,5.0,775000.0
9,2837,Maruti Swift Dzire,maruti,Swift Dzire,10,75220,Dealer,Diesel,Manual,19.3,1248.0,73.90,5.0,390000.0

In [10]:
df.select_dtypes(include="number")
df[["mileage"]]

      mileage
0       19.87
1       33.54
2         NaN
3        15.4
4        16.0
...       ...
15656   20.77
15657   16.09
15658   20.51
15659    18.6
15660   20.28

[15492 rows x 1 columns]

In [27]:
df['selling_price'].isnull().sum()
df['selling_price']=df['selling_price'].fillna(df['selling_price'].mean(), inplace=True)
df['selling_price'].isnull().sum()
import pandas as pd
from sklearn.metrics import mean_absolute_error
mean_price = df["selling_price"].mean()
baseline_preds = [mean_price] * len(df)
mae = mean_absolute_error(df["selling_price"], baseline_preds)
print("Baseline MAE:", mae)

Baseline MAE: 858152.7535099307

C:\Users\neela\AppData\Local\Temp\ipykernel_5988\2642766472.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['selling_price']=df['selling_price'].fillna(df['selling_price'].mean(), inplace=True)